### ISSUE TITLE
UndefinedError: 'fg_color_0' is undefined

### ISSUE THREAD

**Issue by cwm77** [migacode/home-assistant#1]
Hi, I received an error in the display of the NINA warnings in HA for the first time ever. I can't explain why this error message suddenly appears. It is not possible to view the warnings that are actually active. Do you have any idea what the problem could be? Thank you in advance!

UndefinedError: 'fg_color_0' is undefined

**Comment by migacode** [comment]
Thank you very much for your comment.
Oops, it seems that the definition for fg_color_0 has accidentally disappeared during the last update.
To repair this just add
      {% set fg_color_0 = "ffff00" %}
before the line
      {% set fg_color_1 = "888888" %}
Of course, I've also updated the dashboard card - alternatively, you can also use that and adjust your location there.

**Comment by cwm77** [comment]
Many thanks for the prompt reply. The suggestion works.
